{
 "title": "CPE Status",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "serialNumber",
    "label": "Serial Number",
    "query": "show tag values FROM \"CPEDescription\" WITH key=\"serialNumber\""
   }
  ]
 },
 "panels": [
  {
   "title": "Identity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "CPEDescription",
     "select": [
      [
       {
        "params": [
         "Device.DeviceInfo.X_MIKROTIK_SystemIdentity"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "serialNumber", "operator": "=~", "value": "/^$serialNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Hardware Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "CPEDescription",
     "select": [
      [
       {
        "params": [
         "Device.DeviceInfo.HardwareVersion"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "serialNumber", "operator": "=~", "value": "/^$serialNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 0 },
   "targets": [
    {
     "measurement": "CPESystemInfo",
     "select": [
      [
       {
        "params": [
         "Device.DeviceInfo.ProcessStatus.CPUUsage"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "serialNumber", "operator": "=", "value": "C0cYzAcCm/P" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "CPESystemInfo",
     "select": [
      [
       { "params": [ "Device.DeviceInfo.MemoryUsage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "MemoryUsage" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "Device.DeviceInfo.MemoryStatus.Total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TotalMemory" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "serialNumber", "operator": "=~", "value": "/^$serialNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Manufacturer",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "CPEDescription",
     "select": [
      [
       { "params": [ "DeviceID.Manufacturer" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serialNumber", "operator": "=~", "value": "/^$serialNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "s",
   "valueName": "first",
   "targets": [
    {
     "measurement": "CPESystemInfo",
     "select": [
      [
       { "params": [ "Device.DeviceInfo.UpTime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "serialNumber", "operator": "=~", "value": "/^$serialNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Software Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "CPEDescription",
     "select": [
      [
       {
        "params": [
         "Device.DeviceInfo.SoftwareVersion"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "serialNumber", "operator": "=~", "value": "/^$serialNumber$/" }
     ]
    }
   ]
  },
  { "title": "Net Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Internet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "CPEByteStats",
     "select": [
      [
       {
        "params": [
         "Device.Ethernet.Interface.2.Stats.BytesReceived"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "BytesReceived" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "Device.Ethernet.Interface.2.Stats.BytesSent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "BytesSent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "serialNumber", "operator": "=~", "value": "/^$serialNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Local",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "CPEByteStats",
     "select": [
      [
       {
        "params": [
         "Device.Ethernet.Interface.1.Stats.BytesReceived"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "BytesReceived" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "Device.Ethernet.Interface.1.Stats.BytesSent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "BytesSent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "serialNumber", "operator": "=~", "value": "/^$serialNumber$/" }
     ]
    }
   ]
  }
 ]
}